### ISSUE TITLE
Availability on pub.dev

### ISSUE THREAD

**Issue by kaal-dam** [Dokotela/fhir#8]
Did you think this library will soon be available on pub.dev even as an alpha version ?

If not what do you think about adding an "how to use" section in the readme ?

Thanks for the work you're doing on this project

**Comment by Dokotela** [comment]
I've never published a library before, so I was a little nervous about it. But I'm certainly happy to look into it. Either way, a better "how to use" section is probably warranted whether or not it's in pub.dev. Let me see if I can put something together. In the meantime, is there anything specific that you have questions about?

**Comment by kaal-dam** [comment]
Hello, 
Thanks for your answer,
I'll be working soon on an flutter app using stu3 api and i'm wondering if and how to use your library

**Comment by Dokotela** [comment]
Fair enough. I've added a (very basic) how to use section to the readme. As I mention, this is still very much a developing package, so any feedback (whether or not you end up using it) would be welcome.

**Comment by kaal-dam** [comment]
Hello, we've been using your library for some days now and we do have a little feedback

First of all right now we don't had any problem with the API we call and your library, it's really great.
But their is one thing that can be enhanced in our opinion :

We are using the stu3 part of the library and some time we have to check thing like a FhirExtension>Code

If we want to check if the code is the one we want we must do something like `element.code == Code('our_code')`
it would be nice if we just can do `element.code == 'our_code'`

It's not a big thing but it may help developers that don't really know how FHIR work

Have a nice day

**Comment by Dokotela** [comment]
Thanks for the feedback!

You raise a good point and I've gone ahead and made the change. It should now work to say:
```Code('our_code') == Code('our_code')``` and ```Code('our_code') == 'our_code'```

If it doesn't, please let me know. 

Also, I've finally gotten off my ass and created a package. https://pub.dev/packages/fhir

I did reconfigure some of the classes for stu3 to make the formatting look more like my r4 version (still need to do that for dstu2), but I'm sorry if it breaks any of your code.

**Comment by Dokotela** [comment]
Also, are you interacting with an EHR? To really make this useful, I'm going to need to make a Smart on FHIR module, but I haven't gotten to it yet, and I'm curious what others are doing for secure data transfer to/from an EHR.

**Comment by kaal-dam** [comment]
Hello, sorry for the delay i was on holiday.
We aren't using an EHR yet but we may soon, however i'm pretty sure we won't use Smart on FHIR for this one, they have their own third party library that take the FHIR object in entry and do the job.

I have a technical question but i don't know if you prefer i open another issue ou continue here.

Have a nice day.

**Comment by Dokotela** [comment]
I suppose in order to make it easier for anyone else in the future, it would probably be better to start a new issue. I'll close this one and then feel free to start a new one for your technical question!
